var myFullName;
console.log(myFullName);
myFullName="Anushil Sawant";
console.log("After Initilization",myFullName);
myFullName="Anushil Baburao Sawant";
console.log("After Updating",myFullName);
var myLove="I Love only JS";
console.log(myLove);
var fName,lName,age,gender,address,pin,is_married;
fName="Anushil";
console.log("F_Name",fName);
lName="Sawant";
console.log("L_Name",lName);
age=29;
console.log("Age",age);
gender="Male";
console.log("Gender",gender);
address="Navi Mumbai";
console.log("Address",address);
pin=410206;
console.log("Pin",pin);
is_married="Yes";
console.log("Marital Status",is_married);
console.log(fName,lName,age,gender,address,pin,is_married);
